### ISSUE TITLE
yaml.vim

### ISSUE THREAD

**Issue by lzh9102** [flazz/vim-colorschemes#20]
The file colors/yaml.vim is a syntax file, not a colorscheme.

**Comment by flazz** [comment]
PR to remove it please?

**Comment by loreb** [comment]
Hi Franco

There's a few more
I wanted to suggest to "git rm $(grep -l current_syntax colors/*.vim)", but apparently a few
colorschemes match as well (felipec.vim)

Could you at least remove coacl.vim, pic.vim, psql.vim, rtl.vim, scala.vim? (in addition to yaml.vim)
And maybe colorscheme_template.vim?

--

Also, could you add something to your .git/hooks/pre-commit to do some basic checking?
checking against "current_syntax" is ok for everything except felipec.vim,
while something like egrep 'hi.*(term|gui)' works for all except a few themes which are
written in really weird ways (distinguished.vim!!!), and even those match simpler things like "cterm",
except for seoul256-light.vim which just sources seoul256.vim and sets the background.

Ie the idea would be to add some grep magic to pre-commit and a **small** list of exceptions
- does it make sense?

**Comment by flazz** [comment]
Do hooks work inside github? Or is it something everyone would need?

For the other stuff gimme a pr and I'll try to get to it 😀

**Comment by loreb** [comment]
Hooks are small scripts that are executed on your computer when you run "git (whatever)"; see the githooks manpage, it's so short and to the point it's hard to believe it's part of the official git documentation :)

You could add the scripts somewhere in the repo if you feel they'd be useful for others, otherwise they'll get run automagically by git (git, not github) when you run the appropriate command (git commit etc etc)

Re the pr... ok, it's about time I learn how they work. Please be patient if I screw it up...

**Comment by flazz** [comment]
i think we got this worked out thanks!
